const { Router } = require('express');
const router = Router();
const controller = require('../controllers/authController');

//Autentication from user to use the APIs generated by the system
router.post('/api/v1/login/', controller.login);

//Return the user logged in
router.get('/api/v1/profile/',controller.validateToken, controller.profile);

module.exports = router;  