CREATE TABLE IF NOT EXISTS users(
    id_user integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name_user text NOT NULL,
    email_user text NOT NULL,
    pass_user text NOT NULL,
    state_user boolean,
    token text,
    type_user text
);

CREATE TABLE IF NOT EXISTS tickets(
    id_ticket integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user integer REFERENCES users(id_user),
    ticket_desc text,
    created_at date,
    time_duration integer,
    closed_at date,
    state_ticket boolean
);

INSERT INTO users (name_user, email_user, pass_user, state_user) 
            VALUES ('admin','admin@myapp.com','Abc123',TRUE,NULL,'admin');

INSERT INTO users (name_user, email_user, pass_user, state_user) 
            VALUES ('user1','user1@myapp.com','4ser1',TRUE, NULL,'tech');

INSERT INTO users (name_user, email_user, pass_user, state_user) 
            VALUES ('user2','user2@myapp.com','4ser2',TRUE),NULL,'tech';

INSERT INTO users (name_user, email_user, pass_user, state_user) 
            VALUES ('user3','user3@myapp.com','4ser3',TRUE,NULL,'client'); 

INSERT INTO tickets (id_user, ticket_desc, created_at, time_duration, closed_at, state_ticket)
            VALUES ('2','Nueva instalación de soporte de TV LED 55.','2020-05-30','300',NULL,false);

INSERT INTO tickets (id_user, ticket_desc, created_at, time_duration, closed_at, state_ticket)
            VALUES ('2','Cambio de soporte de TV QLED 75 por daño.','2020-06-05 12:02','300','2020-06-05 14:34',true);

INSERT INTO tickets (id_user, ticket_desc, created_at, time_duration, closed_at, state_ticket)
            VALUES ('3','Renovar soporte de TV LED','2020-06-01 10:27','120','2020-06-01 11:53',true);

INSERT INTO tickets (id_user, ticket_desc, created_at, time_duration, closed_at, state_ticket)
            VALUES ('4','Falta un soporte de TV','2020-06-05 16:31','600',NULL,false);